apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
spec:
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
      - name: go-hello
        image: swim0000/go_hello:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
